name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main  # 本番環境
      - staging  # ステージング環境
  workflow_dispatch:  # 手動実行のトリガーを追加

jobs:
  deploy-production:
    name: Deploy to Production
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run Tests
        run: bun test

      - name: Set Environment Config
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "Using production configuration"
            cp wrangler.production.toml wrangler.toml
          else
            echo "Using staging configuration"
            cp wrangler.staging.toml wrangler.toml
          fi

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy